Repository WalkingMachine/sara_install, pull requests merged in 2020-02, with the labels that each got.

#55 Ajout de clarté tuto ros
  README.md
Labels: enhancement

#53 Ne scrape pas les packages qui manques.
  script/scrape_config.sh
Labels: bug

#54 Ajoute la nomenclature de nos branches.
  README.md
Labels: enhancement

#62 Feature/function delete extra packages
  script/_delete_extra_packages.sh
  script/install.sh
Labels: bug, enhancement
